### ISSUE TITLE
Feature Request: support ingress security groups

### ISSUE THREAD

**Issue by chiefy** [terraform-community-modules/tf_aws_sg#20]
Would be cool to allow SGs `ingress` definition [to use other SGs](https://www.terraform.io/docs/providers/aws/r/security_group.html#security_groups).

**Comment by ghost** [comment]
@antonbabenko I am pretty sure, it cannot be done easily with one resource. You can provide either `security_group` or `cidr_block`. I am thinking about `count`, but I am not sure if it will be working for `security_groups`.

**Comment by antonbabenko** [comment]
You are right. First each `aws_security_group` resource should be split into `aws_security_group` and one or more `aws_security_group_rule`. Then introduce a new variable, which will be used in `count` to determine whether the individual resource `aws_security_group_rule` has to be created. Something like `count = "${var.use_sg}"` (on one resource which uses `security_group`) and `count = "${1-var.use_sg}"` (on another resource which uses `cidr_block`).

**Comment by antonbabenko** [comment]
https://github.com/terraform-aws-modules/terraform-aws-security-group - this is the new module, which covers everything from before + something more. If you need help - open an issue there and I will be glad to assist you.
