### ISSUE TITLE
specify a list of cidr_blocks

### ISSUE THREAD

**Issue by fabriziomoscon** [terraform-community-modules/tf_aws_sg#27]
How can I specify a list of CIDR blocks to use in the security group? I am trying the `zookeeper` configuration.

I have a list fo CIDR blocks to pass to the security group, for example:
```
variable "private_cidr_blocks" {
    description = "The IP blocks for the private subnet"
    type        = "list"
    default     = ["10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24"]
}
```

When I apply the plan using the following:
```
...
source_cidr_block = "${join(",", var.private_cidr_block)}"
...

```
I receive a malformed CIDR block error
```bash
* aws_security_group.main_security_group: Error authorizing security group ingress rules: InvalidParameterValue: CIDR block 10.0.1.0/24,10.0.2.0/24,10.0.3.0/24 is malformed
```

**Comment by antonbabenko** [comment]
I don't think it is possible to do using this module right now, but you can open a PR, where you change the `variable "source_cidr_block" {...}` ([for example](https://github.com/terraform-community-modules/tf_aws_sg/blob/master/sg_cassandra/variables.tf#L10)) and add `type = "list"` there.

When this is done you will be able to pass it like this:
```
...
source_cidr_block = ["${var.private_cidr_block}"]
...
```

PS: Pull-request is welcome. :)

**Comment by fabriziomoscon** [comment]
How can I made the code change and at the same time ensuring that it won't break the old references?

**Comment by antonbabenko** [comment]
Sorry for the delay.

To do test and development you have to do the following:
1. git clone of this repo locally and change `source` parameter to the directory where you clone it.
2. edit `tf_aws_sg/sg_web/variables.tf` and add `type = "list"` like this:
  ```hcl
  variable "source_cidr_block" {
    description = "The source CIDR block to allow traffic from"
    type = "list"
  }
  ```
3. change argument inside module to be a list like this `source_cidr_block = ["${var.private_cidr_block}"]`
4. terraform init, plan, apply

Once you are happy with this, open a pull request. Don't forget to update documentation accordingly.

**Comment by ghost** [comment]
@antonbabenko I will implement this feature; moreover, it will be a breaking change for this module.
