### ISSUE TITLE
cassandra sg groups issue

### ISSUE THREAD

**Issue by techfort** [terraform-community-modules/tf_aws_sg#41]
Hi there - brilliant work on tf_aws_sg!
I am getting the error 
```
3 error(s) occurred:

* module.cassandra.module.cassandra_security_group.aws_security_group_rule.ingress_tcp_7199_self: cidr_blocks: should be a list
* module.cassandra.module.cassandra_security_group.aws_security_group_rule.ingress_tcp_9042_self: cidr_blocks: should be a list
* module.cassandra.module.cassandra_security_group.aws_security_group_rule.ingress_tcp_9160_self: cidr_blocks: should be a list
```
I created a PR, this is kind of blocking me so if you don't want to approve that's fine but let me know so i can recreate the sg groups locally in my project.
PR: https://github.com/terraform-community-modules/tf_aws_sg/pull/40

**Comment by antonbabenko** [comment]
Hi @techfort . I assume you are using a recent version of Terraform (0.9.x). The example in `README` is slightly incorrect (I will update it now), so use this example:

```hcl
module "sg_cassandra" {
  source = "github.com/terraform-community-modules/tf_aws_sg//sg_cassandra"

  security_group_name = "test"
  vpc_id = "vpc-xxxxxxxxx"
  source_cidr_block = ["0.0.0.0/0"] # <= this value should be a list
}
```

I am going to close your PR. Let us know if there are any other issues.

**Comment by techfort** [comment]
cheers @antonbabenko this seems reasonable.

**Comment by techfort** [comment]
@antonbabenko just so you know the above did not resolve my issue. You can leave this issue closed if you wish because i re-implemented the security groups locally as i was blocked, but as far as i can tell, this is still not working.

**Comment by antonbabenko** [comment]
Interesting. I have tried it myself yesterday when I wrote my response. Could you please show your code and tell which version of Terraform you use?
