### ISSUE TITLE
Best pratices for how to generate README

### ISSUE THREAD

**Issue by ozbillwang** [terraform-community-modules/tf_aws_sg#45]
Hi Group owner,

I am not sure who I can talk with in `terraform-community-modules`.  I start from here. 

This will be good idea for all repos in this group. 

I recommend generating `REAME` file via useful tool `terraform-docs` (https://github.com/segmentio/terraform-docs) more than manually edit `README.md`.

```
$ brew install terraform-docs
$ terraform-docs md . > README.md

$ cat README.md

## Inputs

| Name | Description | Default | Required |
|------|-------------|:-----:|:-----:|
| security_group_name | The name for the security group | - | yes |
| source_cidr_block | The source CIDR block to allow traffic from | - | yes |
| vpc_id | The VPC this security group will go in | - | yes |

## Outputs

| Name | Description |
|------|-------------|
| security_group_id_web | Output ID of sg_web SG we made |
```

I wrote `terraform best practices` (https://github.com/BWITS/terraform-best-practices#generate-readme-for-each-module-about-input-and-output-variables). This is one of the best practices I recommended. Hope you like this idea. 

We can create another file `USAGE.md` to give the details on how to use this module.

**Comment by antonbabenko** [comment]
@ozbillwang I think that docs are slightly not as important as other best-practices you have shared, mostly because Terraform Registry is able to generate pretty good docs for variables and outputs. Closing for now.
