### ISSUE TITLE
tags in autoscaling group need be list, not map

### ISSUE THREAD

**Issue by ozbillwang** [terraform-community-modules/tf_aws_sg#48]
In most modules here, tags are not used, so we don't really see this issue. 

When using the new module `sg_default` (#44), you will have issue to define the tags.

In terraform resource [aws_autoscaling_group](https://www.terraform.io/docs/providers/aws/r/autoscaling_group.html)

`tags` is defined as list ( not map)

>tags (Optional) A list of tag blocks (maps). Tags documented below.

**Comment by antonbabenko** [comment]
I can't understand the relation between `aws_autoscaling_group` and `sg_default`. ASG is a known resource which has a different structure for tags.

Could you please provide code snippet which is not working as intended?

**Comment by ozbillwang** [comment]
wrong module, closed
