### ISSUE TITLE
Should security descriptions have anything hard-coded at all?

### ISSUE THREAD

**Issue by tehlers320** [terraform-community-modules/tf_aws_sg#49]
-  description = "Security Group ${var.security_group_name}"
+  description = "tf-sg-${var.security_group_name}"

Wouldn't it be better to simply use:
description = "${var.security_group_name}"

letting users of the community rules choose their own names.

**Comment by antonbabenko** [comment]
Very good point. As usual, pull requests are more than welcome. :)

**Comment by epetrovich** [comment]
@antonbabenko  Because of changed description terraform wants to recreate all security groups and recalculate SG ID's for a bunch of production boxes. How to avoid that if I'm fully integrated with community modules?

**Comment by epetrovich** [comment]
Please remove that hardcode and I'll put "Security Group ..." by myself to remain working infrastructure without changes.

**Comment by tehlers320** [comment]
sorry @epetrovich i havent gotten around to giving a merge yet. You could do this while you wait.

```
module "sg_consul" {
  source = "github.com/terraform-community-modules/tf_aws_sg?ref=v0.1.18//sg_consul"
```

@antonbabenko any word on what will happen to this project now that hashicorp has a modules registry? (introduced in 0.10.6)

https://registry.terraform.io/

Ill try and do the proposed PR this weekend.

**Comment by antonbabenko** [comment]
Hi guys!

Sorry that I have not been responding for the last few days but I have just arrived back from HashiConf and going to review and merge several outstanding PRs in several community modules on Monday (25th of September).

@tehlers320 @epetrovich @tfhartmann @jasiek @joestump @hakamadare 
@zimbatm @robinbowes @gstlt @ozbillwang and many others - I am planning to share some thoughts regarding the future of projects inside `terraform-community-modules` GitHub organization during this week. Meanwhile, let's keep pushing PRs as is, and we will migrate them to the new repositories as soon as certain standards are met.

**Comment by zimbatm** [comment]
@antonbabenko thanks, just a heads up; that link is giving me a 404

**Comment by tfhartmann** [comment]
yup, me as well!

**Comment by antonbabenko** [comment]
Here is the blog post about the new registry - https://medium.com/@anton.babenko/welcome-to-terraform-registry-d0192565783d

**Comment by antonbabenko** [comment]
Back to the current issue opened by @tehlers320 . While I was flying last week (16 hours) I was working on a version of this module which will be published to the registry and I need about one day of work to finish it.

Key features are:
1. No code duplication like we currently have almost the same code in each folder
1. Map of ports is defined as local variable in single place in module
1. Support for named security groups (like http, ssh, mysql, etc)
1. Possibility to customize ports, CIDR blocks, IPv6 blocks among other things for any ingress/egress rule

The syntax will look like this (you can imagine that all lists arguments are optional, of course):

```
module "custom_sg" {
  source = "../../modules/sg"

  name        = "sg name"
  description = "sg description"

  vpc_id = "vpc-12345678"

  # open for all:
  ingress_rules = ["http", "mysql"]

  # open co cidr_blocks
  ingress_rules_with_cidr_blocks = [
    {
      rule = "http"
    },
    {
      rule        = "mysql"
      cidr_blocks = "0.0.0.0/0,2.2.2.2/32"
    },
    {
      rule        = "http"
      cidr_blocks = "0.0.0.0/0"
    },
  ]

  # open for security group id:
  ingress_rules_with_source_security_group_id = [
    {
      rule                     = "http"
      source_security_group_id = "sg-12345678"
    },
    {
      rule                     = "mysql"
      source_security_group_id = "sg-12345678"
    },
  ]

  # open for self as a source security group id:
  //  ingress_rules_with_self_security_group_id = [
  //    {
  //      rule = "mysql"
  //    },
  //  ]

  # open custom ports for custom sources
  ingress_ports = [
    {
      from_port                = 10
      to_port                  = 10
      protocol                 = "tcp"
      source_security_group_id = "sg-12345678"
    },
    {
      from_port                = 20
      to_port                  = 30
      protocol                 = "tcp"
      source_security_group_id = "sg-12345678"
    },
    {
      from_port = 30
      to_port   = 40
      protocol  = "tcp"
      self      = true
    },
  ]
}
```

**Comment by antonbabenko** [comment]
https://github.com/terraform-aws-modules/terraform-aws-security-group - this is the new module, which covers everything from before + something more. If you need help - open an issue there and I will be glad to assist.

***I feel that documentation there can still be better, so let's make it together*** :)
