### ISSUE TITLE
InvalidGroup.Duplicate

### ISSUE THREAD

**Issue by TinajaLabs** [terraform-community-modules/tf_aws_sg#53]
I'm not sure if I understand how this works.

I'm seeing this error:
```
aws_security_group.main_security_group: Error creating Security Group: InvalidGroup.Duplicate: The security group 'x_x_x' already exists for VPC 'vpc-00000000'
	status code: 400, request id: bcbf6e06-f159-44a6-b281-2be2628c3b98
````

I want one security group to provide egress for all traffic and ingress for ping/ICMP (seemingly missing in this library) and tcp:22 for ssh.  

It isn't clear how to use all of these from a module without repeating the security group name.

Also, how about tags for the group?  How might I create tags for a name attribute?

Thanks,
Chris.

**Comment by antonbabenko** [comment]
Chris, your assumptions of impossibility are completely valid. There will be an update to the [AWS security group module](https://github.com/terraform-aws-modules/terraform-aws-sg) pretty soon and your request will be possible to accomplish using it. I'd like to keep this issue open as a reminder for myself.

**Comment by antonbabenko** [comment]
https://github.com/terraform-aws-modules/terraform-aws-security-group - this is the new module, which covers everything from before + something more. If you need help - open an issue there and I will be glad to assist you with the transition.
